### ISSUE TITLE
Reference to HSM_MEGA_BEZEL shaders in global Commodore pack preset

### ISSUE THREAD

**Issue by BackSpace54** [TheNamec/megabezel-commodore-pack#1]
Hi,
after looking at the FAQ, searching in libretro forums i don't really know how to get MBZ__2__STD.slangp.

I've installed MBZ pack in version 0.9.094 2021-12-27 Rev 1 (RetroArch 1.9.14 - Win64) in shaders\shaders_slang\bezel\Mega_Bezel.
In the MBZ preset i don't have a MBZ__2__STD.slangp but a MBZ__3__STD.slangp but in your pack the global preset STD_global.slangp is refering to MBZ__2__STD.slangp(?).
So with this basic install your STD shaders get an error because MBZ__2__STD.slangp was not found in MBZ preset...
Of course if i copy MBZ__3__STD.slangp to MBZ__2__STD.slangp or if i modify your global STD preset STD_global.slangp it works.

But some others shader don't works i.e. POT-c1084[day or night].slangp is querying for MBZ__5__POTATO__ZFAST.slangp... but i don't know how to get MBZ__5__POTATO__ZFAST.slangp.

What i'm missing?
Do i need to rename MBZ presets or are some presets missing?
If so where to download them if they are not provide in the MBZ pack?

Tia, best regards.

**Comment by TheNamec** [comment]
Hi BackSpace54, I'm sorry for your mishap with the presets! 

Mega Bezel Reflection Shader is undergoing major changes because of the incoming 1.0 stable release, the  version 0.9.094 2021-12-27 Rev 1 you downloaded is a Release Candidate for public testing and is not compatible with my Commodore Pack. Of course I'm at work to align my presets for the 1.0 stable release, expect announcements soon.

If you cant' wait any longer, you should stick to the Mega Bezel Reflection Shader required version reported in the readme and release pages. Please join the conversation on the official libretro thread https://forums.libretro.com/t/thenamec-mega-bezel-commodore-pack/31523

**Comment by BackSpace54** [comment]
Hi TheNamec, thanks for replying,
ok i understand now :-)
So i've joined the thread you've suggested and posted a question about how to get HSM_Bezel_Reflection_V0.9.022_2021-09-05 (as all download links for HSM are now in 0.9.094 2021-12-27 Rev 1).
Have a nice day.
