### ISSUE TITLE
shader won't start

### ISSUE THREAD

**Issue by B-Nerd** [TheNamec/megabezel-commodore-pack#2]
i have this shader in retroarch/shaders/Mega_Bezel_Community but it won't load i have the mega bezel in retroarch/shaders/shaders_slang/ bezel/Mega_Bezel 
but i found a fix so please change Res to res 
FYI I'm on linux so res & Res are not the same folder they can be both on in the same folder

**Comment by TheNamec** [comment]
Hey thank you for the heads-up, and sorry for the inconvenience and loss of time.

I fixed filename casing in next incoming release RC4, just waiting for RetroArch update to drop the package.

See you there ;)

**Comment by hoderer** [comment]
Yeah! Retroarch 1.11.0 just got released. Really looking forward to RC4. I tried RC3 with the latest Mega Bezel, but the picture didn't look right. I guess RC3 is not really compatible since they changed a few parameters. I hope you don't run into problems with Retroarch and release RC4 within the next days. Are planning a Commodore Plus/4-Preset? I can't thank you enough for your awesome work!

**Comment by TheNamec** [comment]
Heya! Mega Bezel Commodore was updated to RC4.1, hope you can test it soon.

Yep I already got reference material for the so called Commodore 264 series, C16 is done as it basically shares VIC20 chassis. I will add Commodore Plus/4 and C116 as these really have an interesting retro design. I think this will be the penultimate "series pack" after amiga, c64 and vic20, the last being allmighty PET/CBM as I love monochromes. The road to v1.0 seem to be still long ;-)

**Comment by hoderer** [comment]
Thanks for your reply. I noticed some bugs in RC4, but now they're fixed in RC4.1, so THANK YOU! It's really a great experience. Retro-Games never ever looked so perfect. I'm really looking forward to your plus/4-preset and you're right with the interesting retro-design. I really love the design of those machines :)
